/* --------------------------------------------------------------------------
   Theme colours — active palette: Mocha & Apricot  (+ light variant: Mocha & Apricot (Light))
   GENERATED by scripts/generate-theme.js — edit data/palettes.yaml to update.

   Run:  npm run generate-theme

   THEME holds the dark palette (the default); THEME_LIGHT holds the light
   variant. The site defaults to dark regardless of OS preference — light is
   opt-in, applied only when the document is explicitly pinned to
   data-theme="light". All values are #rrggbb hex strings; the helpers convert
   to the formats each layer needs:
     int(hex)        → 0xRRGGBB integer   (Three.js Color / material colours)
     rgba(hex, a)    → 'rgba(r, g, b, a)' (Canvas2D fill/stroke styles)
     glvec(hex)      → [r, g, b] 0..1     (GLSL vec3 literals / uniforms)
------------------------------------------------------------------------------ */

export const THEME = {
  id: 'apricot',
  name: 'Mocha & Apricot',
  bg: '#161110',
  bgAlt: '#2a2321',
  text: '#f4ebe1',
  textMuted: '#a39588',
  textFaint: '#877b6b',
  accent: '#eca670',
  accentHi: '#f1b98a',
  accent2: '#dd775d',
  accent2Hi: '#e79079',
  onAccent: '#2a1a0d',
  heroGradFrom: '#f6d2a8',
  heroGradTo: '#e76f51',
  mapBg: '#100d0c',
  themeColor: '#161110',
  faviconBg: '#161110',
  faviconFg: '#f4a261',
  pins: {
    lived: '#f4a261',
    current: '#ffd166',
    worktrip: '#c97b4a',
    holiday: '#e76f51',
  },
  globe: {
    ocean: '#140b07',
    land: '#2a1810',
    landEurope: '#4a2818',
    coast: '#d98a52',
    coastBright: '#ffe0c0',
    ambient: '#241410',
    keyLight: '#5a3a28',
    rimLight: '#f4a261',
    fillLight: '#e76f51',
    atmInner: '#f4a261',
    atmShell: '#5a2e1f',
    atmHalo: '#e76f51',
    grid: '#b06a3f',
    gridBright: '#f4b87f',
    stars: '#f4ebe1',
    fallback1: '#965f3c',
    fallback2: '#462819',
    fallback3: '#140b07',
  },
  noise: {
    dark: '#161110',
    mid: '#7a4424',
    bright: '#d98a52',
  },
};

export const THEME_LIGHT = {
  id: 'apricot-light',
  name: 'Mocha & Apricot (Light)',
  bg: '#fbf7f3',
  bgAlt: '#f3ebe2',
  text: '#261a12',
  textMuted: '#6e5c4c',
  textFaint: '#93826f',
  accent: '#a15e2f',
  accentHi: '#c77e45',
  accent2: '#b7523c',
  accent2Hi: '#cf6c55',
  onAccent: '#fdf5ef',
  heroGradFrom: '#b25f26',
  heroGradTo: '#c0492f',
  mapBg: '#f0e5d9',
  themeColor: '#fbf7f3',
  faviconBg: '#fbf7f3',
  faviconFg: '#a85a1c',
  pins: {
    lived: '#9c5218',
    current: '#c08a2a',
    worktrip: '#a85a38',
    holiday: '#c0492f',
  },
  globe: {
    ocean: '#ece0d4',
    land: '#dcc1a6',
    landEurope: '#cf9468',
    coast: '#d98a52',
    coastBright: '#a85a30',
    ambient: '#f0e6db',
    keyLight: '#ddb189',
    rimLight: '#b8631f',
    fillLight: '#c0492f',
    atmInner: '#f4a261',
    atmShell: '#f0d0b8',
    atmHalo: '#c0492f',
    grid: '#caa285',
    gridBright: '#a05a30',
    stars: '#6e5c4c',
    fallback1: '#cf9468',
    fallback2: '#e2caba',
    fallback3: '#f0e6db',
  },
  noise: {
    dark: '#fbf7f3',
    mid: '#f3d2b5',
    bright: '#e89a6a',
  },
};

/* The palette shipped as the CSS :root default. */
export const ACTIVE_PALETTE = 'apricot';

/* Every palette, so the picker can recolour the canvases live. The active one
   reuses THEME / THEME_LIGHT rather than repeating them. */
export const PALETTES = {
  forest: {
    id: 'forest',
    name: 'Forest & Brass',
    dark: {
      id: 'forest',
      name: 'Forest & Brass',
      bg: '#0c1410',
      bgAlt: '#1a2721',
      text: '#e8eee5',
      textMuted: '#8a948b',
      textFaint: '#7a837c',
      accent: '#c4a55d',
      accentHi: '#d8ba76',
      accent2: '#75ae8b',
      accent2Hi: '#a1d2b3',
      onAccent: '#1a1408',
      heroGradFrom: '#e6d4a4',
      heroGradTo: '#6db088',
      mapBg: '#080f0b',
      themeColor: '#0c1410',
      faviconBg: '#0c1410',
      faviconFg: '#c8a44d',
      pins: {
        lived: '#6db088',
        current: '#e8c468',
        worktrip: '#4a9e8f',
        holiday: '#d98e54',
      },
      globe: {
        ocean: '#07140d',
        land: '#13251a',
        landEurope: '#2e3d1c',
        coast: '#2f8f6e',
        coastBright: '#b8e8cf',
        ambient: '#10241a',
        keyLight: '#2f5a3e',
        rimLight: '#6db088',
        fillLight: '#c8a44d',
        atmInner: '#6db088',
        atmShell: '#1f4a33',
        atmHalo: '#c8a44d',
        grid: '#3f8f72',
        gridBright: '#6dd0a8',
        stars: '#e8eee5',
        fallback1: '#46785a',
        fallback2: '#163424',
        fallback3: '#08140d',
      },
      noise: {
        dark: '#0c1410',
        mid: '#2c5e42',
        bright: '#7a9e4a',
      },
    },
    light: {
      id: 'forest-light',
      name: 'Forest & Brass (Light)',
      bg: '#f6f8f3',
      bgAlt: '#eaf0e6',
      text: '#18241b',
      textMuted: '#56635a',
      textFaint: '#78857c',
      accent: '#877432',
      accentHi: '#a18c44',
      accent2: '#3c7b5a',
      accent2Hi: '#4c906c',
      onAccent: '#fbfdf8',
      heroGradFrom: '#8a7320',
      heroGradTo: '#2f7d57',
      mapBg: '#e8efe3',
      themeColor: '#f6f8f3',
      faviconBg: '#f6f8f3',
      faviconFg: '#2f7d57',
      pins: {
        lived: '#2f7d57',
        current: '#9a7d28',
        worktrip: '#2f7d6e',
        holiday: '#8a6a2a',
      },
      globe: {
        ocean: '#dde9e0',
        land: '#b9d0bd',
        landEurope: '#8fb06a',
        coast: '#2f8f6e',
        coastBright: '#1d6b50',
        ambient: '#e4efe6',
        keyLight: '#a8c8a8',
        rimLight: '#2f7d57',
        fillLight: '#8a7320',
        atmInner: '#6db088',
        atmShell: '#c0e0cc',
        atmHalo: '#8a7320',
        grid: '#8fb89e',
        gridBright: '#3f8f72',
        stars: '#56635a',
        fallback1: '#6a9a7a',
        fallback2: '#c8dccd',
        fallback3: '#e4efe6',
      },
      noise: {
        dark: '#f6f8f3',
        mid: '#cfe0c5',
        bright: '#9ab87a',
      },
    },
  },
  apricot: { id: 'apricot', name: 'Mocha & Apricot', dark: THEME, light: THEME_LIGHT },
  crimson: {
    id: 'crimson',
    name: 'Crimson & Rust',
    dark: {
      id: 'crimson',
      name: 'Crimson & Rust',
      bg: '#1a1010',
      bgAlt: '#302121',
      text: '#f0e6e3',
      textMuted: '#a3908c',
      textFaint: '#8a7b78',
      accent: '#cc5257',
      accentHi: '#de726c',
      accent2: '#ba693e',
      accent2Hi: '#d28e5f',
      onAccent: '#1a0404',
      heroGradFrom: '#f2c9b0',
      heroGradTo: '#c2632e',
      mapBg: '#140b0b',
      themeColor: '#1a1010',
      faviconBg: '#1a1010',
      faviconFg: '#d64550',
      pins: {
        lived: '#e8626c',
        current: '#f2b56a',
        worktrip: '#a8516b',
        holiday: '#d0703a',
      },
      globe: {
        ocean: '#140807',
        land: '#2a1310',
        landEurope: '#3d1f1a',
        coast: '#b85040',
        coastBright: '#f0c0b0',
        ambient: '#241010',
        keyLight: '#5a2a28',
        rimLight: '#d64550',
        fillLight: '#c2632e',
        atmInner: '#d64550',
        atmShell: '#4a1f1c',
        atmHalo: '#c2632e',
        grid: '#a04a40',
        gridBright: '#e08070',
        stars: '#f0e6e3',
        fallback1: '#8a4540',
        fallback2: '#3a1815',
        fallback3: '#140807',
      },
      noise: {
        dark: '#1a1010',
        mid: '#6e2828',
        bright: '#b8543a',
      },
    },
    light: {
      id: 'crimson-light',
      name: 'Crimson & Rust (Light)',
      bg: '#faf6f3',
      bgAlt: '#f2e8e4',
      text: '#241715',
      textMuted: '#6e5852',
      textFaint: '#94817b',
      accent: '#ae3234',
      accentHi: '#c54549',
      accent2: '#994f2b',
      accent2Hi: '#b5653a',
      onAccent: '#fdf3f1',
      heroGradFrom: '#c2632e',
      heroGradTo: '#b81f2a',
      mapBg: '#efe3de',
      themeColor: '#faf6f3',
      faviconBg: '#faf6f3',
      faviconFg: '#b81f2a',
      pins: {
        lived: '#b81f2a',
        current: '#c2812a',
        worktrip: '#8a3a52',
        holiday: '#a04a1c',
      },
      globe: {
        ocean: '#e6dcd6',
        land: '#d3b3a4',
        landEurope: '#c2855f',
        coast: '#b85040',
        coastBright: '#8a2f28',
        ambient: '#efe3dd',
        keyLight: '#d8a48c',
        rimLight: '#b81f2a',
        fillLight: '#c2632e',
        atmInner: '#d64550',
        atmShell: '#ecc4b6',
        atmHalo: '#c2632e',
        grid: '#c39588',
        gridBright: '#9c463c',
        stars: '#6e5852',
        fallback1: '#c2855f',
        fallback2: '#ddc3b8',
        fallback3: '#efe3dd',
      },
      noise: {
        dark: '#faf6f3',
        mid: '#f1cdbb',
        bright: '#e79a7b',
      },
    },
  },
};

/* Resolve the palette in effect for the current document, along both axes:
   which palette (data-palette, default ACTIVE_PALETTE) and which variant
   (light only when explicitly pinned to data-theme="light" — everything else,
   including no pin and SSR, is dark). */
export function getTheme() {
  let paletteId = ACTIVE_PALETTE;
  let variant = 'dark';
  const root = typeof document !== 'undefined' ? document.documentElement : null;
  if (root) {
    /* getAttribute first, dataset second: js/ui.js reads the same attributes
       that way, and it keeps this working against the minimal document stubs
       the tests use. */
    const read = (attr, key) => (typeof root.getAttribute === 'function'
      ? root.getAttribute(attr)
      : (root.dataset || {})[key]);
    const pid = read('data-palette', 'palette');
    if (pid && PALETTES[pid]) paletteId = pid;
    if (read('data-theme', 'theme') === 'light') variant = 'light';
  }
  const entry = PALETTES[paletteId] || PALETTES[ACTIVE_PALETTE];
  return variant === 'light' ? entry.light : entry.dark;
}

/* '#rrggbb' → 0xRRGGBB integer. */
export function int(hex) {
  return parseInt(String(hex).replace('#', ''), 16);
}

/* '#rrggbb' (+ alpha 0..1) → 'rgba(r, g, b, a)' string. */
export function rgba(hex, alpha = 1) {
  const n = int(hex);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${alpha})`;
}

/* '#rrggbb' → [r, g, b] floats 0..1, rounded for tidy GLSL source. */
export function glvec(hex) {
  const n = int(hex);
  const f = (c) => Math.round((c / 255) * 1e4) / 1e4;
  return [f((n >> 16) & 255), f((n >> 8) & 255), f(n & 255)];
}
