/* --------------------------------------------------------------------------
   Theme colours — active palette: Forest & Brass
   GENERATED by scripts/generate-theme.js — edit data/palettes.yaml to update.

   Run:  npm run generate-theme

   THEME holds #rrggbb hex strings. The helpers convert to the formats each
   rendering layer needs:
     int(hex)        → 0xRRGGBB integer   (Three.js Color / material colours)
     rgba(hex, a)    → 'rgba(r, g, b, a)' (Canvas2D fill/stroke styles)
     glvec(hex)      → [r, g, b] 0..1     (GLSL vec3 literals / uniforms)
------------------------------------------------------------------------------ */

export const THEME = {
  id: 'forest',
  name: 'Forest & Brass',
  bg: '#0a120e',
  bgAlt: '#0f1a14',
  text: '#e8eee5',
  textMuted: '#8a948b',
  textFaint: '#767f78',
  accent: '#c8a44d',
  accentHi: '#dcb968',
  accent2: '#6db088',
  accent2Hi: '#9bd4b0',
  onAccent: '#1a1408',
  heroGradFrom: '#e6d4a4',
  heroGradTo: '#6db088',
  mapBg: '#08100c',
  themeColor: '#0a120e',
  faviconBg: '#0a120e',
  faviconFg: '#c8a44d',
  pins: {
    lived: '#6db088',
    current: '#e8c468',
    worktrip: '#4a9e8f',
    holiday: '#d98e54',
  },
  globe: {
    ocean: '#07140d',
    land: '#13251a',
    landEurope: '#2e3d1c',
    coast: '#2f8f6e',
    coastBright: '#b8e8cf',
    ambient: '#10241a',
    keyLight: '#2f5a3e',
    rimLight: '#6db088',
    fillLight: '#c8a44d',
    atmInner: '#6db088',
    atmShell: '#1f4a33',
    atmHalo: '#c8a44d',
    grid: '#3f8f72',
    gridBright: '#6dd0a8',
    stars: '#e8eee5',
    fallback1: '#46785a',
    fallback2: '#163424',
    fallback3: '#08140d',
  },
  noise: {
    dark: '#0a120e',
    mid: '#2c5e42',
    bright: '#7a9e4a',
  },
};

/* '#rrggbb' → 0xRRGGBB integer. */
export function int(hex) {
  return parseInt(String(hex).replace('#', ''), 16);
}

/* '#rrggbb' (+ alpha 0..1) → 'rgba(r, g, b, a)' string. */
export function rgba(hex, alpha = 1) {
  const n = int(hex);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${alpha})`;
}

/* '#rrggbb' → [r, g, b] floats 0..1, rounded for tidy GLSL source. */
export function glvec(hex) {
  const n = int(hex);
  const f = (c) => Math.round((c / 255) * 1e4) / 1e4;
  return [f((n >> 16) & 255), f((n >> 8) & 255), f(n & 255)];
}
