/* --------------------------------------------------------------------------
   Theme colours — active palette: Crimson & Rust  (+ light variant: Crimson & Rust (Light))
   GENERATED by scripts/generate-theme.js — edit data/palettes.yaml to update.

   Run:  npm run generate-theme

   THEME holds the dark palette (the default); THEME_LIGHT holds the light
   variant. The site defaults to dark regardless of OS preference — light is
   opt-in, applied only when the document is explicitly pinned to
   data-theme="light". All values are #rrggbb hex strings; the helpers convert
   to the formats each layer needs:
     int(hex)        → 0xRRGGBB integer   (Three.js Color / material colours)
     rgba(hex, a)    → 'rgba(r, g, b, a)' (Canvas2D fill/stroke styles)
     glvec(hex)      → [r, g, b] 0..1     (GLSL vec3 literals / uniforms)
------------------------------------------------------------------------------ */

export const THEME = {
  id: 'crimson',
  name: 'Crimson & Rust',
  bg: '#120a0a',
  bgAlt: '#1a0f0e',
  text: '#f0e6e3',
  textMuted: '#a3908c',
  textFaint: '#8a7b78',
  accent: '#cc5257',
  accentHi: '#de726c',
  accent2: '#ba693e',
  accent2Hi: '#d28e5f',
  onAccent: '#fbeae9',
  heroGradFrom: '#f2c9b0',
  heroGradTo: '#c2632e',
  mapBg: '#0e0808',
  themeColor: '#120a0a',
  faviconBg: '#120a0a',
  faviconFg: '#d64550',
  pins: {
    lived: '#d64550',
    current: '#f2b56a',
    worktrip: '#a8516b',
    holiday: '#c2632e',
  },
  globe: {
    ocean: '#140807',
    land: '#2a1310',
    landEurope: '#3d1f1a',
    coast: '#b85040',
    coastBright: '#f0c0b0',
    ambient: '#241010',
    keyLight: '#5a2a28',
    rimLight: '#d64550',
    fillLight: '#c2632e',
    atmInner: '#d64550',
    atmShell: '#4a1f1c',
    atmHalo: '#c2632e',
    grid: '#a04a40',
    gridBright: '#e08070',
    stars: '#f0e6e3',
    fallback1: '#8a4540',
    fallback2: '#3a1815',
    fallback3: '#140807',
  },
  noise: {
    dark: '#120a0a',
    mid: '#6e2828',
    bright: '#b8543a',
  },
};

export const THEME_LIGHT = {
  id: 'crimson-light',
  name: 'Crimson & Rust (Light)',
  bg: '#faf6f3',
  bgAlt: '#f2e8e4',
  text: '#241715',
  textMuted: '#6e5852',
  textFaint: '#94817b',
  accent: '#ae3234',
  accentHi: '#c54549',
  accent2: '#994f2b',
  accent2Hi: '#b5653a',
  onAccent: '#fdf3f1',
  heroGradFrom: '#c2632e',
  heroGradTo: '#b81f2a',
  mapBg: '#efe3de',
  themeColor: '#faf6f3',
  faviconBg: '#faf6f3',
  faviconFg: '#b81f2a',
  pins: {
    lived: '#b81f2a',
    current: '#c2812a',
    worktrip: '#8a3a52',
    holiday: '#a04a1c',
  },
  globe: {
    ocean: '#e6dcd6',
    land: '#d3b3a4',
    landEurope: '#c2855f',
    coast: '#b85040',
    coastBright: '#8a2f28',
    ambient: '#efe3dd',
    keyLight: '#d8a48c',
    rimLight: '#b81f2a',
    fillLight: '#c2632e',
    atmInner: '#d64550',
    atmShell: '#ecc4b6',
    atmHalo: '#c2632e',
    grid: '#c39588',
    gridBright: '#9c463c',
    stars: '#6e5852',
    fallback1: '#c2855f',
    fallback2: '#ddc3b8',
    fallback3: '#efe3dd',
  },
  noise: {
    dark: '#faf6f3',
    mid: '#f1cdbb',
    bright: '#e79a7b',
  },
};

/* Resolve the palette active for the current document. Light only when the
   document is explicitly pinned to data-theme="light"; everything else
   (no pin, data-theme="dark", or SSR / no DOM) is the dark THEME. */
export function getTheme() {
  if (typeof document !== 'undefined' && document.documentElement) {
    const pinned = document.documentElement.dataset && document.documentElement.dataset.theme;
    if (pinned === 'light') return THEME_LIGHT;
  }
  return THEME;
}

/* '#rrggbb' → 0xRRGGBB integer. */
export function int(hex) {
  return parseInt(String(hex).replace('#', ''), 16);
}

/* '#rrggbb' (+ alpha 0..1) → 'rgba(r, g, b, a)' string. */
export function rgba(hex, alpha = 1) {
  const n = int(hex);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${alpha})`;
}

/* '#rrggbb' → [r, g, b] floats 0..1, rounded for tidy GLSL source. */
export function glvec(hex) {
  const n = int(hex);
  const f = (c) => Math.round((c / 255) * 1e4) / 1e4;
  return [f((n >> 16) & 255), f((n >> 8) & 255), f(n & 255)];
}
