/* public/feed.xml is generated by scripts/generate-feed.mjs. Entry
   timestamps come from git history, which moves with every commit, so —
   like the sitemap and unlike llms.txt — this suite checks shape and
   content rather than byte-for-byte drift: an exact-equality test would
   fail on any commit that touches a page without regenerating the feed. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { OUT } from '../scripts/generate-feed.mjs';
import { PROJECTS } from '../data/projects.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const xml = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';

test('feed.xml exists and is an Atom feed', () => {
  assert.ok(xml, 'public/feed.xml is missing — run `npm run generate-feed`');
  assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>\n/);
  assert.match(xml, /<feed xmlns="http:\/\/www\.w3\.org\/2005\/Atom">/);
  assert.match(xml, /<link href="https:\/\/[^"]+\/feed\.xml" rel="self"/);
});

test('feed.xml carries one entry per project plus the /now entry', () => {
  const count = (xml.match(/<entry>/g) || []).length;
  assert.equal(count, PROJECTS.length + 1,
    `expected ${PROJECTS.length + 1} entries (projects + now), found ${count} — run \`npm run generate-feed\``);
  for (const p of PROJECTS) {
    assert.ok(xml.includes(`<title>${p.title.replaceAll('&', '&amp;')}</title>`),
      `feed.xml is missing project: ${p.title}`);
  }
});

test('feed.xml /now entry matches the date the page shows', () => {
  const html = fs.readFileSync(path.join(ROOT, 'now.html'), 'utf8');
  const m = /Last updated\s+(\d{1,2}\s+\w+\s+\d{4})/.exec(html);
  assert.ok(m, 'now.html no longer carries a "Last updated" line');
  const iso = new Date(`${m[1]} UTC`).toISOString().slice(0, 10);
  assert.ok(xml.includes(`/now.html#${iso}`),
    `feed.xml /now entry is stale (page says ${iso}) — run \`npm run generate-feed\``);
});

test('feed.xml timestamps are RFC 3339 and links are https', () => {
  const dates = [...xml.matchAll(/<updated>([^<]+)<\/updated>/g)].map((m) => m[1]);
  assert.ok(dates.length >= 2, 'expected feed-level and entry <updated> elements');
  for (const d of dates) {
    assert.match(d, /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/,
      `bad Atom timestamp: ${d}`);
  }
  for (const [, href] of xml.matchAll(/href="([^"]+)"/g)) {
    assert.match(href, /^https:\/\//, `feed.xml link is not https: ${href}`);
  }
});

test('feed.xml has no unescaped ampersands', () => {
  const bad = xml.match(/&(?!amp;|lt;|gt;|quot;|apos;|#\d+;)/g) || [];
  assert.deepEqual(bad, [], 'raw & in feed.xml — escapeXml missed a field');
});

test('index.html advertises the feed for autodiscovery', () => {
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  assert.match(html, /<link rel="alternate" type="application\/atom\+xml"[^>]*href="\/feed\.xml"/,
    'index.html <head> is missing the Atom autodiscovery link');
});
