/* public/feed.xml is generated by scripts/generate-feed.mjs. Entry
   timestamps come from git history, which moves with every commit, so —
   like the sitemap and unlike llms.txt — this suite checks shape and
   content rather than byte-for-byte drift: an exact-equality test would
   fail on any commit that touches a page without regenerating the feed. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { OUT } from '../scripts/generate-feed.mjs';
import { PROJECTS } from '../data/projects.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const xml = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';

test('feed.xml exists and is an Atom feed', () => {
  assert.ok(xml, 'public/feed.xml is missing — run `npm run generate-feed`');
  assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>\n/);
  assert.match(xml, /<feed xmlns="http:\/\/www\.w3\.org\/2005\/Atom">/);
  assert.match(xml, /<link href="https:\/\/[^"]+\/feed\.xml" rel="self"/);
});

test('feed.xml carries one entry per project plus the /now entry', () => {
  const count = (xml.match(/<entry>/g) || []).length;
  assert.equal(count, PROJECTS.length + 1,
    `expected ${PROJECTS.length + 1} entries (projects + now), found ${count} — run \`npm run generate-feed\``);
  for (const p of PROJECTS) {
    assert.ok(xml.includes(`<title>${p.title.replaceAll('&', '&amp;')}</title>`),
      `feed.xml is missing project: ${p.title}`);
  }
});

test('feed.xml /now entry matches the date the page shows', () => {
  const html = fs.readFileSync(path.join(ROOT, 'now.html'), 'utf8');
  const m = /Last updated\s+(\d{1,2}\s+\w+\s+\d{4})/.exec(html);
  assert.ok(m, 'now.html no longer carries a "Last updated" line');
  const iso = new Date(`${m[1]} UTC`).toISOString().slice(0, 10);
  assert.ok(xml.includes(`/now.html#${iso}`),
    `feed.xml /now entry is stale (page says ${iso}) — run \`npm run generate-feed\``);
});

test('feed.xml timestamps are RFC 3339 and links are https', () => {
  const dates = [...xml.matchAll(/<updated>([^<]+)<\/updated>/g)].map((m) => m[1]);
  assert.ok(dates.length >= 2, 'expected feed-level and entry <updated> elements');
  for (const d of dates) {
    assert.match(d, /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/,
      `bad Atom timestamp: ${d}`);
  }
  for (const [, href] of xml.matchAll(/href="([^"]+)"/g)) {
    assert.match(href, /^https:\/\//, `feed.xml link is not https: ${href}`);
  }
});

test('feed.xml has no unescaped ampersands', () => {
  const bad = xml.match(/&(?!amp;|lt;|gt;|quot;|apos;|#\d+;)/g) || [];
  assert.deepEqual(bad, [], 'raw & in feed.xml — escapeXml missed a field');
});

/* Autodiscovery is a per-page convention, not a homepage one: a reader pointed
   at any URL on this site should find the feed, which is why the <link> is in
   the head of all 21 pages. It was asserted on index.html alone, and that gap
   was not theoretical — the scaffold in scripts/new-project.js had no such
   link, so the next project page created with the documented command would
   have shipped without one and nothing here would have said so. */
const AUTODISCOVERY = /<link rel="alternate" type="application\/atom\+xml"[^>]*href="\/feed\.xml"/;

function allPages(dir = ROOT, prefix = '') {
  const skip = new Set(['node_modules', 'dist', '.git', '.cache', 'drafts', 'test']);
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || skip.has(entry.name)) continue;
    if (entry.isDirectory()) out.push(...allPages(path.join(dir, entry.name), `${prefix}${entry.name}/`));
    else if (entry.name.endsWith('.html')) out.push(prefix + entry.name);
  }
  return out.sort();
}

const PAGES = allPages();

test('every page advertises the feed for autodiscovery', () => {
  assert.ok(PAGES.length >= 20, `only ${PAGES.length} pages globbed — the directory read is wrong`);
  assert.ok(PAGES.includes('index.html') && PAGES.some((p) => p.startsWith('projects/')));

  const missing = PAGES.filter(
    (p) => !AUTODISCOVERY.test(fs.readFileSync(path.join(ROOT, p), 'utf8')),
  );
  assert.deepEqual(missing, [],
    `these pages have no Atom autodiscovery <link>: ${missing.join(', ')}`);
});

/* ─────────────────────────────────────────────────────────────────────────────
   Entry dates are editorial, not file mtimes.

   <updated> used to be the project page's last git commit date, which is right
   for a sitemap's <lastmod> and wrong here: a reader uses <updated> to decide
   an item is worth surfacing again, so every commit that touched a project page
   for unrelated reasons — a CSP hash, a typo, an SVG marker id — pushed that
   project back to the top of every subscriber's feed. Eight of fourteen entries
   once carried the dates of two audits that changed no prose.

   The reversion this guards against is subtle and would look like a tidy-up:
   `lastmodFor(page)` is still in the module (the /now entry uses it as a
   fallback), so putting it back on the project loop is a one-line change that
   breaks nothing visible and no other assertion would notice. Pinning the
   dates to data/projects.js is what makes that change fail.
──────────────────────────────────────────────────────────────────────────────*/
test('feed.xml project dates come from data/projects.js, not git history', async () => {
  const { PROJECTS } = await import('../data/projects.js');
  const entries = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map((m) => m[1]);

  for (const p of PROJECTS) {
    const entry = entries.find((e) => e.includes(`<title>${p.title.replace(/&/g, '&amp;')}</title>`));
    assert.ok(entry, `feed.xml has no entry for "${p.title}"`);
    const updated = /<updated>([^<]+)<\/updated>/.exec(entry)[1];
    const expected = /^\d{4}-\d{2}-\d{2}$/.test(p.updated || '')
      ? `${p.updated}T00:00:00Z`
      : `${parseInt(p.year, 10)}-01-01T00:00:00Z`;
    assert.equal(updated, expected,
      `"${p.title}" <updated> is ${updated}, expected ${expected}. If this reads as a `
      + 'git commit timestamp, the project loop in scripts/generate-feed.mjs has gone '
      + 'back to lastmodFor() — see the note there.');
  }
});

test('feed.xml entry dates are stable across commits (no time-of-day component)', () => {
  /* A git-derived timestamp carries the commit's clock time; an editorial date
     is midnight UTC by construction. Asserting the shape catches the reversion
     even for a project whose `year` happens to match its last commit year. */
  const entries = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map((m) => m[1]);
  const projectEntries = entries.filter((e) => !e.includes('/now.html'));
  assert.ok(projectEntries.length >= 10, `only ${projectEntries.length} project entries found`);
  for (const e of projectEntries) {
    const updated = /<updated>([^<]+)<\/updated>/.exec(e)[1];
    assert.match(updated, /T00:00:00Z$/,
      `${updated} has a wall-clock time — project entry dates must be midnight UTC`);
  }
});
