'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const {
  ALIASES,
  normalizeCountry,
  deriveFromLocations,
  compileCountries,
  toCountriesJs,
} = require('../scripts/generate-countries.js');

test('normalizeCountry resolves common aliases to TopoJSON names', () => {
  assert.equal(normalizeCountry('USA'), 'United States of America');
  assert.equal(normalizeCountry('UK'), 'United Kingdom');
  assert.equal(normalizeCountry('United Kingdom'), 'United Kingdom');
  // Unknown names pass through trimmed
  assert.equal(normalizeCountry('  Italy '), 'Italy');
});

test('ALIASES is an object mapping strings to strings', () => {
  assert.equal(typeof ALIASES, 'object');
  assert.equal(ALIASES.USA, 'United States of America');
});

test('deriveFromLocations classifies lived vs visited from the last comma token', () => {
  const source = {
    pins: [
      { type: 'lived', name: 'Berlin, Germany' },
      { type: 'current', name: 'San Sebastián, Spain' },
      { type: 'holiday', name: 'Paris, France' },
      { type: 'worktrip', name: 'London, UK' },
    ],
    trips: [
      { name: 'USA 2011', cities: ['Chicago, Illinois, USA', 'New York City, New York, USA'] },
      { name: 'Sicily', cities: ['Palermo, Sicily, Italy'] },
    ],
  };
  const { lived, visited } = deriveFromLocations(source);
  assert.ok(lived.includes('Germany'));
  assert.ok(lived.includes('Spain'));
  assert.ok(visited.includes('France'));
  // UK normalized to United Kingdom
  assert.ok(visited.includes('United Kingdom'));
  // USA normalized
  assert.ok(visited.includes('United States of America'));
  // Italy appears via a trip city — visited (not lived here)
  assert.ok(visited.includes('Italy'));
  // A lived country never also appears in visited
  assert.ok(!visited.includes('Germany'));
  assert.ok(!visited.includes('Spain'));
});

test('compileCountries returns sorted, de-duplicated, disjoint lists', () => {
  const source = {
    pins: [
      { type: 'lived', name: 'Berlin, Germany' },
      { type: 'holiday', name: 'Munich, Germany' },
      { type: 'holiday', name: 'Paris, France' },
    ],
    trips: [],
  };
  const out = compileCountries({ locations: source });
  assert.deepEqual(out.lived, ['Germany']);
  assert.deepEqual(out.visited, ['France']);
  // disjoint
  for (const c of out.lived) assert.ok(!out.visited.includes(c));
});

test('compileCountries honours an explicit countries.yaml override list', () => {
  const overrides = {
    countries: [
      { name: 'Italy', status: 'lived' },
      { name: 'Japan', status: 'visited' },
    ],
  };
  const out = compileCountries({ countries: overrides });
  assert.deepEqual(out.lived, ['Italy']);
  assert.deepEqual(out.visited, ['Japan']);
});

test('toCountriesJs emits a valid ESM module exporting COUNTRIES', () => {
  const js = toCountriesJs({ lived: ['Italy'], visited: ['France', 'Japan'] }, 'data/countries.yaml');
  assert.match(js, /export const COUNTRIES =/);
  assert.match(js, /"lived"/);
  assert.match(js, /"visited"/);
  assert.match(js, /Generated by/);
});
