'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const { compileUnesco, toUnescoJs } = require('../scripts/generate-unesco.js');

const SAMPLE = {
  continents: [
    {
      name: 'Europe',
      countries: [
        {
          name: 'Italy',
          sites: [
            { name: 'Historic Centre of Rome', url: 'https://whc.unesco.org/en/list/91', year: 2018 },
            { name: 'Venice and its Lagoon', url: 'https://whc.unesco.org/en/list/394' },
          ],
        },
        {
          name: 'Spain',
          sites: [
            { name: 'Works of Antoni Gaudí', url: 'https://whc.unesco.org/en/list/320' },
          ],
        },
      ],
    },
    {
      name: 'Asia',
      countries: [
        { name: 'Japan', sites: [{ name: 'Historic Kyoto', url: 'https://whc.unesco.org/en/list/688' }] },
      ],
    },
  ],
};

test('compileUnesco preserves the continent → country → site hierarchy', () => {
  const out = compileUnesco(SAMPLE);
  assert.equal(out.continents.length, 2);
  assert.equal(out.continents[0].name, 'Europe');
  assert.equal(out.continents[0].countries[0].name, 'Italy');
  assert.equal(out.continents[0].countries[0].sites.length, 2);
  assert.equal(out.continents[0].countries[0].sites[0].url, 'https://whc.unesco.org/en/list/91');
});

test('compileUnesco keeps an optional year and tolerates its absence', () => {
  const out = compileUnesco(SAMPLE);
  assert.equal(out.continents[0].countries[0].sites[0].year, 2018);
  assert.ok(!('year' in out.continents[0].countries[0].sites[1]));
});

test('compileUnesco drops sites missing a name or url', () => {
  const out = compileUnesco({
    continents: [
      {
        name: 'Europe',
        countries: [
          { name: 'France', sites: [{ name: 'No URL' }, { url: 'https://x' }, { name: 'Ok', url: 'https://ok' }] },
        ],
      },
    ],
  });
  assert.equal(out.continents[0].countries[0].sites.length, 1);
  assert.equal(out.continents[0].countries[0].sites[0].name, 'Ok');
});

test('compileUnesco rejects http (non-https) and javascript: URLs', () => {
  const out = compileUnesco({
    continents: [
      {
        name: 'Europe',
        countries: [
          {
            name: 'Italy',
            sites: [
              { name: 'evil', url: 'javascript:alert(1)' },
              { name: 'insecure', url: 'http://whc.unesco.org/en/list/1' },
              { name: 'good', url: 'https://whc.unesco.org/en/list/1' },
            ],
          },
        ],
      },
    ],
  });
  assert.equal(out.continents[0].countries[0].sites.length, 1);
  assert.equal(out.continents[0].countries[0].sites[0].name, 'good');
});

test('compileUnesco tolerates an empty / malformed source', () => {
  assert.deepEqual(compileUnesco({}).continents, []);
  assert.deepEqual(compileUnesco(null).continents, []);
});

test('toUnescoJs emits an ESM module exporting UNESCO', () => {
  const js = toUnescoJs(compileUnesco(SAMPLE), 'data/unesco.yaml');
  assert.match(js, /export const UNESCO =/);
  assert.match(js, /Generated by/);
  assert.match(js, /globalThis\.UNESCO/);
});
