'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const { compileLinks, compileLink, toLinksJs } = require('../scripts/generate-links.js');

const SAMPLE = {
  categories: [
    {
      name: 'AI / ML',
      blurb: 'People I read to keep up with the field.',
      links: [
        { name: "Lil'Log", url: 'https://lilianweng.github.io', description: 'Deep, careful explainers.' },
        { name: 'Distill', url: 'https://distill.pub' },
      ],
    },
    {
      name: 'Engineering',
      links: [
        { name: 'Julia Evans', url: 'https://jvns.ca', description: 'Wizard zines and debugging.' },
      ],
    },
  ],
};

test('compileLinks preserves the category → link hierarchy and order', () => {
  const out = compileLinks(SAMPLE);
  assert.equal(out.categories.length, 2);
  assert.equal(out.categories[0].name, 'AI / ML');
  assert.equal(out.categories[0].links.length, 2);
  assert.equal(out.categories[0].links[0].name, "Lil'Log");
  assert.equal(out.categories[0].links[0].url, 'https://lilianweng.github.io');
  assert.equal(out.categories[1].name, 'Engineering');
});

test('compileLinks keeps an optional category blurb and tolerates its absence', () => {
  const out = compileLinks(SAMPLE);
  assert.equal(out.categories[0].blurb, 'People I read to keep up with the field.');
  assert.ok(!('blurb' in out.categories[1]));
});

test('compileLinks keeps an optional link description and tolerates its absence', () => {
  const out = compileLinks(SAMPLE);
  assert.equal(out.categories[0].links[0].description, 'Deep, careful explainers.');
  assert.ok(!('description' in out.categories[0].links[1]));
});

test('compileLinks drops links missing a name or url', () => {
  const out = compileLinks({
    categories: [
      { name: 'Misc', links: [{ name: 'No URL' }, { url: 'https://x.example' }, { name: 'Ok', url: 'https://ok.example' }] },
    ],
  });
  assert.equal(out.categories[0].links.length, 1);
  assert.equal(out.categories[0].links[0].name, 'Ok');
});

test('compileLinks rejects http (non-https), javascript: and protocol-relative URLs', () => {
  const out = compileLinks({
    categories: [
      {
        name: 'Misc',
        links: [
          { name: 'evil', url: 'javascript:alert(1)' },
          { name: 'insecure', url: 'http://example.com' },
          { name: 'schemeless', url: '//example.com' },
          { name: 'good', url: 'https://example.com' },
        ],
      },
    ],
  });
  assert.equal(out.categories[0].links.length, 1);
  assert.equal(out.categories[0].links[0].name, 'good');
});

test('compileLinks drops categories that end up with no valid links', () => {
  const out = compileLinks({
    categories: [
      { name: 'Empty', links: [{ name: 'bad' }] },
      { name: 'Has one', links: [{ name: 'ok', url: 'https://ok.example' }] },
    ],
  });
  assert.equal(out.categories.length, 1);
  assert.equal(out.categories[0].name, 'Has one');
});

test('compileLink trims whitespace around fields', () => {
  const link = compileLink({ name: '  Spaced  ', url: '  https://example.com  ', description: '  hi  ' });
  assert.equal(link.name, 'Spaced');
  assert.equal(link.url, 'https://example.com');
  assert.equal(link.description, 'hi');
});

test('compileLinks tolerates an empty / malformed source', () => {
  assert.deepEqual(compileLinks({}).categories, []);
  assert.deepEqual(compileLinks(null).categories, []);
  assert.deepEqual(compileLinks({ categories: 'nope' }).categories, []);
});

test('toLinksJs emits an ESM module exporting LINKS', () => {
  const js = toLinksJs(compileLinks(SAMPLE), 'data/links.yaml');
  assert.match(js, /export const LINKS =/);
  assert.match(js, /Generated by/);
  assert.match(js, /globalThis\.LINKS/);
});
