const test = require('node:test');
const assert = require('node:assert/strict');

const {
  parseYaml,
  compileLocations,
  toLocationsJs,
} = require('../scripts/generate-locations.js');

test('parseYaml parses the expected locations schema', () => {
  const parsed = parseYaml(`
pins:
  - type: lived
    name: Crema, Italy
    info: Home
trips:
  - name: Trip A
    cycleSec: 22
    cities:
      - name: Milan, Italy
        lat: 45.4642
        lon: 9.19
      - name: Rome, Italy
        lat: 41.9028
        lon: 12.49
regions:
  - name: Sardinia, Italy
    radius: 1.4
    lat: 40.12
    lon: 9.07
`);

  assert.equal(parsed.pins[0].name, 'Crema, Italy');
  assert.equal(parsed.trips[0].cities[0].name, 'Milan, Italy');
  assert.equal(parsed.regions[0].radius, 1.4);
});

test('compileLocations assigns defaults and keeps explicit coordinates', async () => {
  const source = {
    pins: [
      { type: 'lived', name: 'Crema, Italy', lat: 45.36, lon: 9.68, info: 'Home town' },
      { type: 'unexpected', name: 'Paris, France', lat: 48.8566, lon: 2.3522, info: 'Holiday' },
    ],
    trips: [
      {
        name: 'Trip A',
        cities: [
          { name: 'Milan, Italy', lat: 45.4642, lon: 9.19 },
          { name: 'Rome, Italy', lat: 41.9028, lon: 12.49 },
        ],
      },
    ],
    regions: [
      { name: 'Sardinia, Italy', lat: 40.12, lon: 9.07, radius: 1.4, info: 'Holiday' },
    ],
  };

  const compiled = await compileLocations(source, {
    geocode: false,
    cache: '/tmp/stocastico-test-cache.json',
  });

  assert.equal(compiled.geocodeRequests, 0);
  assert.equal(compiled.pins[1].type, 'lived');
  assert.equal(compiled.trips[0].color, '#ff6b6b');
  assert.equal(compiled.regions[0].color, '#ff8c42');
});

test('compileLocations preserves all valid pin types', async () => {
  const source = {
    pins: [
      { type: 'lived', name: 'A', lat: 1, lon: 1, info: '' },
      { type: 'current', name: 'B', lat: 2, lon: 2, info: '' },
      { type: 'worktrip', name: 'C', lat: 3, lon: 3, info: '' },
      { type: 'holiday', name: 'D', lat: 4, lon: 4, info: '' },
    ],
    trips: [],
    regions: [],
  };
  const compiled = await compileLocations(source, { geocode: false, cache: '/tmp/stocastico-test-types.json' });
  assert.equal(compiled.pins[0].type, 'lived');
  assert.equal(compiled.pins[1].type, 'current');
  assert.equal(compiled.pins[2].type, 'worktrip');
  assert.equal(compiled.pins[3].type, 'holiday');
});

test('toLocationsJs returns executable JS declaration', () => {
  const js = toLocationsJs(
    {
      pins: [{ type: 'lived', name: 'Crema, Italy', lat: 45.36, lon: 9.68, info: 'Home town' }],
      trips: [],
      regions: [],
    },
    'data/locations.yaml',
  );

  assert.match(js, /export const LOCATIONS =/);
  assert.match(js, /Crema, Italy/);
  assert.match(js, /globalThis\.LOCATIONS = LOCATIONS/);
});

test('compileLocations reports place and YAML line when coordinates are missing with --no-geocode', async () => {
  const source = {
    pins: [
      { type: 'lived', name: 'Unknown Place XYZ', info: 'Missing coords' },
    ],
    trips: [],
    regions: [],
  };

  const sourceRaw = `
pins:
  - type: lived
    name: Unknown Place XYZ
    info: Missing coords
trips: []
regions: []
`;

  await assert.rejects(
    () => compileLocations(source, {
      geocode: false,
      cache: '/tmp/stocastico-test-no-geocode.json',
      sourceRaw,
      sourcePath: 'data/locations.yaml',
    }),
    /Missing coordinates for "Unknown Place XYZ" at pins\[0\] \(data\/locations\.yaml:4\)/,
  );
});

test('compileLocations reports geocoding no-results with place and YAML line', async () => {
  const source = {
    pins: [
      { type: 'lived', name: 'No Result City ABC', info: 'Missing coords' },
    ],
    trips: [],
    regions: [],
  };

  const sourceRaw = `
pins:
  - type: lived
    name: No Result City ABC
    info: Missing coords
trips: []
regions: []
`;

  const originalFetch = global.fetch;
  global.fetch = async () => ({
    ok: true,
    async json() {
      return [];
    },
  });

  try {
    await assert.rejects(
      () => compileLocations(source, {
        geocode: true,
        cache: '/tmp/stocastico-test-geocode-empty.json',
        sourceRaw,
        sourcePath: 'data/locations.yaml',
      }),
      /Geocoding failed for "No Result City ABC" at pins\[0\] \(data\/locations\.yaml:4\): No geocoding results/,
    );
  } finally {
    global.fetch = originalFetch;
  }
});

/* ── Generated headers are platform-independent ──────────────────────────────
   Four generators (locations, countries, links, unesco) write "Generated by …
   from <source>" into the file they emit, and built that source string with
   path.relative(), whose separator is the host OS's. data/locations.js was
   committed from a Windows run naming "data\locations.yaml", so every run on
   Linux or in CI rewrote that line back — a standing one-line diff in a file
   the project tells you never to hand-edit.

   Asserting on the committed artefacts rather than calling toPosix() and
   comparing it to itself: what matters is that the files in the repo are the
   ones a Linux CI run would produce, which is the thing that was actually
   wrong. A fifth generator that copies the old pattern fails here too, since
   the check is over the whole data directory. */
test('generated data modules name their source with forward slashes', () => {
  const fs = require('node:fs');
  const nodePath = require('node:path');
  const dir = nodePath.join(__dirname, '..', 'data');
  const generated = fs.readdirSync(dir).filter((f) => f.endsWith('.js'));
  assert.ok(generated.length >= 4, 'expected generated data modules to exist');
  for (const file of generated) {
    const head = fs.readFileSync(nodePath.join(dir, file), 'utf8').slice(0, 400);
    const m = /Generated by [^\n]*? from ([^\s*]+)/.exec(head);
    if (!m) continue; /* not one of the header-carrying generators */
    assert.ok(
      !m[1].includes('\\'),
      `data/${file} names its source as "${m[1]}" — a Windows path separator `
      + 'baked into a generated file. Re-run the generator on this machine; the '
      + 'fix in the generator is scripts/lib/paths.js toPosix().',
    );
  }
});

/* toPosix itself, on the one input that matters. */
test('toPosix normalises the host separator away', () => {
  const { toPosix } = require('../scripts/lib/paths.js');
  const nodePath = require('node:path');
  assert.equal(toPosix(['data', 'locations.yaml'].join(nodePath.sep)), 'data/locations.yaml');
  assert.equal(toPosix('data/locations.yaml'), 'data/locations.yaml');
  assert.equal(toPosix(''), '');
  assert.equal(toPosix(null), '');
});
