'use strict';
/* ─────────────────────────────────────────────────────────────────────────────
   scripts/lib/paths.js — path helpers shared by the CJS generators.

   Exists for one reason: four generators (locations, countries, links, unesco)
   write a "Generated by … from <source>" header into the file they emit, and
   they built that source string with path.relative(), whose separator is the
   host OS's. The committed data/locations.js therefore named its source as
   "data\locations.yaml" — from a Windows run — and every subsequent run on
   Linux or in CI rewrote that one line back to a forward slash. A permanent
   one-line diff in a file the project explicitly tells you never to hand-edit,
   sitting in the way of any real change to it.

   A generated artefact should be a function of its input, not of the machine
   that happened to produce it. toPosix() is that function's missing piece.
──────────────────────────────────────────────────────────────────────────────*/
const path = require('node:path');

/** Normalise a filesystem path to forward slashes, on every platform. */
function toPosix(p) {
  return String(p == null ? '' : p).split(path.sep).join('/');
}

module.exports = { toPosix };
