#!/usr/bin/env node
'use strict';

/*
  generate-unesco.js

  Compiles data/unesco.yaml (UNESCO World Heritage sites Stefano has visited,
  grouped continent → country → site) into the generated ESM module
  data/unesco.js, consumed by renderUnescoAccordion() in js/main.js on the
  travel page.

  Site URLs are restricted to https:// so the rendered links can never become
  a javascript:/data: injection vector.
*/

const fs = require('node:fs');
const path = require('node:path');

const { parseYaml } = require('./lib/yaml');

function isSafeHttpsUrl(url) {
  return typeof url === 'string' && /^https:\/\/\S+$/i.test(url.trim());
}

function compileSite(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const name = typeof raw.name === 'string' ? raw.name.trim() : '';
  const url = typeof raw.url === 'string' ? raw.url.trim() : '';
  if (!name || !isSafeHttpsUrl(url)) return null;
  const site = { name, url };
  if (raw.year !== undefined && raw.year !== null && `${raw.year}`.trim() !== '') {
    site.year = raw.year;
  }
  return site;
}

function compileUnesco(source) {
  const continents = [];
  const rawContinents = (source && Array.isArray(source.continents)) ? source.continents : [];

  for (const rawContinent of rawContinents) {
    if (!rawContinent || typeof rawContinent !== 'object') continue;
    const continentName = typeof rawContinent.name === 'string' ? rawContinent.name.trim() : '';
    if (!continentName) continue;

    const countries = [];
    for (const rawCountry of (Array.isArray(rawContinent.countries) ? rawContinent.countries : [])) {
      if (!rawCountry || typeof rawCountry !== 'object') continue;
      const countryName = typeof rawCountry.name === 'string' ? rawCountry.name.trim() : '';
      if (!countryName) continue;

      const sites = [];
      for (const rawSite of (Array.isArray(rawCountry.sites) ? rawCountry.sites : [])) {
        const site = compileSite(rawSite);
        if (site) sites.push(site);
      }
      if (sites.length) countries.push({ name: countryName, sites });
    }
    if (countries.length) continents.push({ name: continentName, countries });
  }

  return { continents };
}

function toUnescoJs(data, sourcePath) {
  const payload = JSON.stringify(data, null, 2);
  return `/* eslint-disable */
/* Generated by scripts/generate-unesco.js from ${sourcePath} */
export const UNESCO = ${payload};

if (typeof globalThis !== 'undefined') globalThis.UNESCO = UNESCO;
`;
}

function parseArgs(argv) {
  const out = { input: 'data/unesco.yaml', output: 'data/unesco.js', dryRun: false };
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--input' || arg === '-i') out.input = argv[++i];
    else if (arg === '--output' || arg === '-o') out.output = argv[++i];
    else if (arg === '--dry-run') out.dryRun = true;
    else if (arg === '--help' || arg === '-h') out.help = true;
    else throw new Error(`Unknown argument: ${arg}`);
  }
  return out;
}

function printHelp() {
  console.log(`Usage:
  node scripts/generate-unesco.js [options]

Options:
  -i, --input <path>    YAML source (default: data/unesco.yaml)
  -o, --output <path>   generated JS output (default: data/unesco.js)
      --dry-run         print the module without writing it
  -h, --help            show this help
`);
}

function main() {
  const options = parseArgs(process.argv);
  if (options.help) {
    printHelp();
    return;
  }
  const inputPath = path.resolve(options.input);
  const outputPath = path.resolve(options.output);
  if (!fs.existsSync(inputPath)) throw new Error(`Input file not found: ${inputPath}`);

  const source = parseYaml(fs.readFileSync(inputPath, 'utf8'));
  const data = compileUnesco(source);
  const js = toUnescoJs(data, path.relative(process.cwd(), inputPath));

  const siteCount = data.continents.reduce(
    (n, c) => n + c.countries.reduce((m, k) => m + k.sites.length, 0),
    0,
  );

  if (options.dryRun) {
    console.log(js);
    return;
  }
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, js, 'utf8');
  console.log(`Generated ${path.relative(process.cwd(), outputPath)}`);
  console.log(`Continents: ${data.continents.length}, Sites: ${siteCount}`);
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    console.error(`Error: ${err.message}`);
    process.exitCode = 1;
  }
}

module.exports = { compileUnesco, compileSite, isSafeHttpsUrl, toUnescoJs, parseYaml };
