#!/usr/bin/env node
'use strict';

/*
  generate-links.js

  Compiles data/links.yaml (a curated blogroll of high-quality sites and
  technical blogs Stefano follows, grouped category → link) into the generated
  ESM module data/links.js, consumed by renderLinks() in js/main.js on the
  links page.

  Link URLs are restricted to https:// so the rendered links can never become
  a javascript:/data:/protocol-relative injection vector.
*/

const fs = require('node:fs');
const path = require('node:path');

const { parseYaml } = require('./lib/yaml');

function isSafeHttpsUrl(url) {
  return typeof url === 'string' && /^https:\/\/\S+$/i.test(url.trim());
}

function compileLink(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const name = typeof raw.name === 'string' ? raw.name.trim() : '';
  const url = typeof raw.url === 'string' ? raw.url.trim() : '';
  if (!name || !isSafeHttpsUrl(url)) return null;
  const link = { name, url };
  if (typeof raw.description === 'string' && raw.description.trim() !== '') {
    link.description = raw.description.trim();
  }
  return link;
}

function compileLinks(source) {
  const categories = [];
  const rawCategories = (source && Array.isArray(source.categories)) ? source.categories : [];

  for (const rawCategory of rawCategories) {
    if (!rawCategory || typeof rawCategory !== 'object') continue;
    const categoryName = typeof rawCategory.name === 'string' ? rawCategory.name.trim() : '';
    if (!categoryName) continue;

    const links = [];
    for (const rawLink of (Array.isArray(rawCategory.links) ? rawCategory.links : [])) {
      const link = compileLink(rawLink);
      if (link) links.push(link);
    }
    if (!links.length) continue;

    const category = { name: categoryName, links };
    if (typeof rawCategory.blurb === 'string' && rawCategory.blurb.trim() !== '') {
      category.blurb = rawCategory.blurb.trim();
    }
    categories.push(category);
  }

  return { categories };
}

function toLinksJs(data, sourcePath) {
  const payload = JSON.stringify(data, null, 2);
  return `/* eslint-disable */
/* Generated by scripts/generate-links.js from ${sourcePath} */
export const LINKS = ${payload};

if (typeof globalThis !== 'undefined') globalThis.LINKS = LINKS;
`;
}

function parseArgs(argv) {
  const out = { input: 'data/links.yaml', output: 'data/links.js', dryRun: false };
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--input' || arg === '-i') out.input = argv[++i];
    else if (arg === '--output' || arg === '-o') out.output = argv[++i];
    else if (arg === '--dry-run') out.dryRun = true;
    else if (arg === '--help' || arg === '-h') out.help = true;
    else throw new Error(`Unknown argument: ${arg}`);
  }
  return out;
}

function printHelp() {
  console.log(`Usage:
  node scripts/generate-links.js [options]

Options:
  -i, --input <path>    YAML source (default: data/links.yaml)
  -o, --output <path>   generated JS output (default: data/links.js)
      --dry-run         print the module without writing it
  -h, --help            show this help
`);
}

function main() {
  const options = parseArgs(process.argv);
  if (options.help) {
    printHelp();
    return;
  }
  const inputPath = path.resolve(options.input);
  const outputPath = path.resolve(options.output);
  if (!fs.existsSync(inputPath)) throw new Error(`Input file not found: ${inputPath}`);

  const source = parseYaml(fs.readFileSync(inputPath, 'utf8'));
  const data = compileLinks(source);
  const js = toLinksJs(data, path.relative(process.cwd(), inputPath));

  const linkCount = data.categories.reduce((n, c) => n + c.links.length, 0);

  if (options.dryRun) {
    console.log(js);
    return;
  }
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, js, 'utf8');
  console.log(`Generated ${path.relative(process.cwd(), outputPath)}`);
  console.log(`Categories: ${data.categories.length}, Links: ${linkCount}`);
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    console.error(`Error: ${err.message}`);
    process.exitCode = 1;
  }
}

module.exports = { compileLinks, compileLink, isSafeHttpsUrl, toLinksJs, parseYaml };
